export enum Quality {
  "Consumer Grade" = 1,
  "Base Grade" = 1,
  "Industrial Grade" = 2,
  "Mil-Spec Grade" = 3,
  "High Grade" = 3,
  "Distinguished" = 3,
  "Restricted" = 4,
  "Remarkable" = 4,
  "Exceptional" = 4,
  "Classified" = 5,
  "Exotic" = 5,
  "Superior" = 5,
  "Covert" = 6,
  "Extraordinary" = 6,
  "Master" = 6,
  "Rare Special" = 7,
  "Gloves" = 7,
  "Knives" = 7,
  "Contraband" = 8,
}
